POST http://localhost:3000/api/livereport
Content-Type: application/json
Accept: application/json

{
    "Perekaman":2,
	"Cetak_Baru":3,
	"Perubahan_Elemen":4,
	"Pergantian_Rusak":1,
	"Pergantian_Hilang":1,
	"Perihal_Lainnya":1,
	"Sisa_Blanko":1,
	"Akta_Kelahiran_Dibawah_18":1,
	"Akta_Kelahiran_Diatas_18":1,
	"Akta_Kematian":1,
	"Cetak_Kia":1,
	"Kartu_Keluarga":1,
	"Pindah":1,
	"Datang":1,
	"Aktivasi_Ikd":1,
	"Total_Aktivasi_Ikd":1
}

### Get Data
GET http://localhost:3000/api/livereport
Accept: application/json

##	Agr Laju Pertumbuhan Penduduk
### Update
PUT http://localhost:3000/api/agrlajupertumbuhanpendudukupdate?kode=13.76&semester=2&tahun=24
Content-Type: application/json
Accept: application/json

{
	"Pria":524,
	"Wanita":552
}

### Delete
DELETE http://localhost:3000/api/agrlajupertumbuhanpendudukdelete?kode=13.76&semester=2&tahun=24
Accept: application/json

### Get
GET http://localhost:3000/api/agrlajupertumbuhanpenduduk?kode=13.76&semester=2&tahun=25
Accept: application/json

### Get All
GET http://localhost:3000/api/agrlajupertumbuhanpendudukall
Accept: application/json


### Update category by id
PUT http://localhost:3000/api/news/5
Accept: application/json
Content-Type: application/json

{
  	"Title": "Test",
	"Slug": "test5",
	"Content": "Test text",
	"Thumbnail_url": "Laporan Harian (23).png",
	"Author_id": 1,
	"Category_id": 1,
	"Status": "published",
	"Create_at": "2025-01-01 00:00:00",
	"Update_at": "2025-01-01 00:00:00"
}


### Create category by id
POST http://localhost:3000/api/users
Accept: application/json
Content-Type: application/json

{
  	"Nama": "Test",
	"Username": "test511",
	"Email": "Test 1text",
	"Password": "Laporan Harian (23).png",
	"Role": "admin",
	"Create_at": "2025-01-01 00:00:00",
	"Update_at": "2025-01-01 00:00:00"
}

### Update category by id
PUT http://localhost:3000/api/users/1
Accept: application/json
Content-Type: application/json

{
  	"Nama": "Test1111",
	"Username": "test5",
	"Email": "Test text",
	"Password": "Laporan Harian (23).png",
	"Role": "admin",
	"Create_at": "2025-01-01 00:00:00",
	"Update_at": "2025-01-01 00:00:00"
}