// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"backend/app"
	"backend/controller"
	"backend/repository"
	"backend/service"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

func InitializedController() *http.Server {
	agrLajuPertumbuhanPendudukRepository := repository.NewAgrLajuPertumbuhanPendudukRepository()
	db := app.NewDB()
	agrLajuPertumbuhanPendudukService := service.NewAgrLajuPertumbuhanPendudukServiceService(agrLajuPertumbuhanPendudukRepository, db)
	agrLajuPertumbuhanPendudukController := controller.NewAgrLajuPertumbuhanPendudukController(agrLajuPertumbuhanPendudukService)
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository, db)
	userController := controller.NewUserController(userService)
	liveReportRepository := repository.NewLiveReportRepository()
	liveReportService := service.NewLiveReportService(db, liveReportRepository)
	liveReportController := controller.NewLiveReportController(liveReportService)
<<<<<<< HEAD
	beritaController := controller.NewBeritaController()
	routerController := app.NewFooBarController(agrLajuPertumbuhanPendudukController, userController, liveReportController, beritaController)
=======
	newsRepository := repository.NewNewsRepository()
	newsService := service.NewNewsService(db, newsRepository)
	newsController := controller.NewNewsController(newsService)
	routerController := app.NewFooBarController(agrLajuPertumbuhanPendudukController, userController, liveReportController, newsController)
>>>>>>> 4cf54d18ea3962da852d30ffce9b30c94ee43d69
	router := app.NewRouter(routerController)
	server := NewServer(router)
	return server
}

// wire.go:

var agrlajupertumbuhanpendudukSet = wire.NewSet(repository.NewAgrLajuPertumbuhanPendudukRepository, service.NewAgrLajuPertumbuhanPendudukServiceService, controller.NewAgrLajuPertumbuhanPendudukController)

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)

var liveReportSet = wire.NewSet(repository.NewLiveReportRepository, service.NewLiveReportService, controller.NewLiveReportController)

var newsSet = wire.NewSet(repository.NewNewsRepository, service.NewNewsService, controller.NewNewsController)
