// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"backend/app"
	"backend/controller"
	"backend/repository"
	"backend/service"
)

// Injectors from wire.go:

func InitializedAgrLajuPertumbuhanPenduduk() controller.AgrLajuPertumbuhanPendudukController {
	agrLajuPertumbuhanPendudukRepository := repository.NewAgrLajuPertumbuhanPendudukRepository()
	db := app.NewDB()
	agrLajuPertumbuhanPendudukService := service.NewAgrLajuPertumbuhanPendudukServiceService(agrLajuPertumbuhanPendudukRepository, db)
	agrLajuPertumbuhanPendudukController := controller.NewAgrLajuPertumbuhanPendudukController(agrLajuPertumbuhanPendudukService)
	return agrLajuPertumbuhanPendudukController
}
