SELECT 
	KODE,
	"TIDAK/BELUM SEKOLAH",
	"BELUM TAMAT SD/SEDERAJAT",
	"TAMAT SD/SEDERAJAT",
	"SLTP/SEDERAJAT",
	"SLTA/SEDERAJAT",
	"DIPLOMA I/II",
	"AKADEMI/DIPLOMA III/S.MUDA_J",
	"DIPLOMA IV/STRATA I",
	"STRATA II",
	"STRATA III" 
FROM AGR_PDDKN_VERT apv 
ORDER BY KODE